name: Synpress CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  #audit:
  # run only on main branch and pull requests
  # if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
  # runs-on: ubuntu-latest

  # steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Audit dependencies
  #     run: npm audit --audit-level=critical

  #   - name: Lockfile lint
  #     run: npx --yes lockfile-lint -p package-lock.json --type npm --allowed-hosts npm --validate-https --empty-hostname false

  build:
    #needs: audit
    # run only on audit success or audit skipped
    if: always() #&& (needs.audit.result == 'success' || needs.audit.result == 'skipped')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-16-

      # fix: permission issues on ghactions+docker+npm@7
      - name: Chown workspace
        run: chown -R $(whoami) .

      - name: Install dependencies
        run: npm install --legacy-peer-deps --prefer-offline --no-audit

      - name: Lint
        # run only on main branch and pull requests
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
        run: npm run lint

  # e2e:
  #   needs: build
  #   # run only on main branch
  #   if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
  #   runs-on: ubuntu-latest

  #   container:
  #     image: ghcr.io/synthetixio/docker-e2e/ubuntu:16.14
  #     credentials:
  #       username: synthetixio
  #       password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Set npm cache directory
  #       run: npm config set cache .npm-cache --global
  #       continue-on-error: true

  #     - name: Cache node modules
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           .npm-cache
  #           node_modules
  #         key: ${{ runner.os }}-ubuntu-e2e-16-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-ubuntu-e2e-16-
  #       continue-on-error: true

  #     # fix: permission issues on ghactions+docker+npm@7
  #     - name: Chown workspace
  #       run: chown -R $(whoami) .

  #     - name: Install dependencies
  #       run: npm install --legacy-peer-deps --prefer-offline --no-audit
  #       env:
  #         CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache/Cypress

  #     - name: Run e2e tests
  #       run: npm run test:e2e:ci
  #       env:
  #         SKIP_METAMASK_SETUP: ${{ secrets.SKIP_METAMASK_SETUP }}
  #         CYPRESS_PRIVATE_KEY_WITH_FUNDS: ${{ secrets.CYPRESS_PRIVATE_KEY_WITH_FUNDS }}
  #         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache/Cypress

  #     - name: Archive e2e artifacts
  #       uses: actions/upload-artifact@v3
  #       if: always()
  #       with:
  #         name: e2e-artifacts
  #         path: |
  #           tests/e2e/videos
  #           tests/e2e/screenshots
  #       continue-on-error: true
