name: Release CI

on:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: release

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-16-

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@josepmc'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps --prefer-offline --no-audit

      - name: npm config
        run: echo "registry=https://npm.pkg.github.com/@josepmc" >> .npmrc

      - name: Release
        run: |
          npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
      - run: npm pack
      - run: npm publish $(ls josepmc-synpress-*.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/delete-package-versions@v3
        with:
          package-name: '@josepmc/synpress'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: 'true'
